name: Build & Deploy

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist/

  deploy:
    needs: build
    uses: PazerOP/pr-preview-action/.github/workflows/preview.yml@v1
    with:
      artifact-name: build
    secrets: inherit
